version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_events_db
    environment:
      POSTGRES_USER: edem
      POSTGRES_PASSWORD: edem
      POSTGRES_DB: my_events_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: